//@version=5
indicator("VPA Indicator", overlay=true)

showLongs = input.bool(true, title="Show Long Signals")
showShorts = input.bool(true, title="Show Short Signals")
showVolumeAnomalies = input.bool(true, title="Show Volume Anomalies")
priceLevelsString = input.string("0.0", title="Price Levels (comma-delimited list)")
volumeSMALength = input(50, title="Volume SMA Length")
acceptableVolumeThreshold = input(0.0, title="Acceptable Volume Threshold (% more than average)")
proximityThreshold = input(0.15, title="Proximity Threshold ($)")
strengthThreshold = input(0.55, title="Strength Threshold (%)")
priceLevels = str.split(priceLevelsString, ",")

volumeSMA = ta.sma(volume, volumeSMALength)
sufficientVolume = volume > volumeSMA + (volumeSMA * acceptableVolumeThreshold)
isVolumeHigher = volume > volume[1]

// Get current, previous, and previous previous candles buy/sell volume and average the two previous candle's volume
buyVolume = (high==low) ? 0 : volume *  (close-low)  / (high-low)
sellVolume = (high==low) ? 0 : volume * (high-close) / (high-low)
prevBuyVolume = (high[1]==low[1]) ? 0 : volume[1] *  (close[1]-low[1])  / (high[1]-low[1])
prevSellVolume = (high[1]==low[1]) ? 0 : volume[1] * (high[1]-close[1]) / (high[1]-low[1])
prevPrevBuyVolume = (high[2]==low[2]) ? 0 : volume[2] *  (close[2]-low[2])  / (high[2]-low[2])
prevPrevSellVolume = (high[2]==low[2]) ? 0 : volume[2] * (high[2]-close[2]) / (high[2]-low[2])
prevAvgBuyVolume = (prevBuyVolume + prevPrevBuyVolume) / 2
prevAvgSellVolume = (prevSellVolume + prevPrevSellVolume) / 2

// Calculate the open/close and highLow range of the current and previous candles
candleOpenCloseRange = math.abs(close - open)
candleHighLowRange = math.abs(high - low)
prevCandleOpenCloseRange = math.abs(close[1] - open[1])
prevCandleHighLowRange = math.abs(high[1] - low[1])

// Only want to include dojis in the signals if they have higher than average volume
isDoji = math.abs(close - open) < (candleHighLowRange * 0.1) and volume > volume[1] * 1.33

// Determine if the current candle is close enough to a price level based on the proximity threshold. 
// A candle is at support if any part of the bottom wick is within the proximity threshold of a price level
// A candle is at resistance if any part of the top wick is within the proximity threshold of a price level
isAtSupport = false
isAtResistance = false
for level in priceLevels
    levelFloat = str.tonumber(level)
    priceLevelRangeStart = levelFloat - proximityThreshold
    priceLevelRangeEnd = levelFloat + proximityThreshold
    if ((isDoji and open > levelFloat) or close > levelFloat) and (priceLevelRangeStart >= open and priceLevelRangeStart <= low) or (priceLevelRangeEnd >= open and priceLevelRangeEnd <= low) or (open >= priceLevelRangeStart and open <= priceLevelRangeEnd) or (low >= priceLevelRangeStart and low <= priceLevelRangeEnd)
        isAtSupport := true
        break
for level in priceLevels
    levelFloat = str.tonumber(level)
    priceLevelRangeStart = levelFloat - proximityThreshold
    priceLevelRangeEnd = levelFloat + proximityThreshold
    if ((isDoji and open < levelFloat) or close < levelFloat) and (priceLevelRangeStart >= open and priceLevelRangeStart <= high) or (priceLevelRangeEnd >= open and priceLevelRangeEnd <= high) or (open >= priceLevelRangeStart and open <= priceLevelRangeEnd) or (high >= priceLevelRangeStart and high <= priceLevelRangeEnd)
        isAtResistance := true
        break

// Calculate top/bottom wicks and determine sell/buy pressure for determining if the candle is relatively strong/weak
prevCandleTopWick = close[1] > open[1] ? math.abs(high[1] - close[1]) : math.abs(high[1] - open[1])
prevCandleBottomWick = close[1] > open[1] ? math.abs(open[1] - low[1]) : math.abs(close[1] - low[1])
significantSellPressureOnPreviousCandle = prevCandleTopWick > math.abs(high[1] - low[1]) - prevCandleTopWick
significantBuyPressureOnPreviousCandle = prevCandleBottomWick > math.abs(high[1] - low[1]) - prevCandleBottomWick

// If the previous candle was red the current candle must be green and one of the below must apply:
//      1. engulf at least strength threshold % of the previous candle's range
//      2. the previous candle must have significant buy pressure and engulf at least half strength threshold % of the previous candle's range
// If the previous candle was green the current candle must be green and more aggressive based on body and bottom wick.
candleIsRelativelyStrong = close > open and (close[1] < open[1] and (candleOpenCloseRange > prevCandleOpenCloseRange * strengthThreshold or (significantBuyPressureOnPreviousCandle and candleOpenCloseRange > prevCandleOpenCloseRange * strengthThreshold * 0.5)) or (close[1] > open[1] and (candleOpenCloseRange > prevCandleOpenCloseRange or math.abs(low - open) > prevCandleHighLowRange * strengthThreshold)))
// The top wick should not be larger than the body + the bottom wick
bullishDirectional = math.abs(high - close) < math.abs(close - low)
isBullishCandle = candleIsRelativelyStrong and bullishDirectional

// If the previous candle was green the current candle must be red and one of the below must apply:
//      1. either engulf at least strength threshold % of the previous candle's range
//      2. the previous candle must have significant sell pressure and engulf at least half strength threshold % of the previous candle's range. 
// If the previous candle was red the current candle must be red and more aggressive based on body and top wick.
candleIsRelativelyWeak = close < open and (close[1] > open[1] and (candleOpenCloseRange > prevCandleOpenCloseRange * strengthThreshold or (significantSellPressureOnPreviousCandle and candleOpenCloseRange > prevCandleOpenCloseRange * strengthThreshold * 0.5)) or (close[1] < open[1] and (candleOpenCloseRange > prevCandleOpenCloseRange or math.abs(high - open) > prevCandleHighLowRange * strengthThreshold)))
// The bottom wick should not be larger than the body + the top wick
bearishDirectional = math.abs(close - low) < math.abs(high - close)
isBearishCandle = candleIsRelativelyWeak and bearishDirectional

// Plot volume anomalies and indications of long and short signals
// + signals are candles that have more volume than the previous candle
longSignal = showLongs and (isBullishCandle or isDoji) and buyVolume > prevAvgBuyVolume and (sellVolume < prevAvgSellVolume or isDoji) and sufficientVolume and isAtSupport and buyVolume > sellVolume
shortSignal = showShorts and (isBearishCandle or isDoji) and sellVolume > prevAvgSellVolume and (buyVolume < prevAvgBuyVolume or isDoji) and sufficientVolume and isAtResistance and sellVolume > buyVolume
bullishVolumeAnomaly = showVolumeAnomalies and close < open and close[1] < open[1] and candleOpenCloseRange < prevCandleOpenCloseRange and volume > volume[1] and sufficientVolume
bearishVolumeAnomaly = showVolumeAnomalies and close > open and close[1] > open[1] and candleOpenCloseRange < prevCandleOpenCloseRange and volume > volume[1] and sufficientVolume

plotshape(bullishVolumeAnomaly and not longSignal, title="Volume Anomaly", location=location.belowbar, color=color.rgb(255, 238, 88), transp=0, style=shape.triangleup, text="Anomaly")
plotshape(bearishVolumeAnomaly and not shortSignal, title="Volume Anomaly", location=location.abovebar, color=color.rgb(255, 238, 88), transp=0, style=shape.triangledown, text="Anomaly")
plotshape(longSignal and not bullishVolumeAnomaly and not isVolumeHigher, title="Long", location=location.belowbar, color=color.rgb(30, 143, 55), transp=0, style=shape.triangleup, text="Long")
plotshape(shortSignal and not bearishVolumeAnomaly and not isVolumeHigher, title="Short", location=location.abovebar, color=color.rgb(241, 90, 103), transp=0, style=shape.triangledown, text="Short")
plotshape(longSignal and not bullishVolumeAnomaly and isVolumeHigher, title="Long+", location=location.belowbar, color=color.rgb(30, 143, 55), transp=0, style=shape.triangleup, text="Long+")
plotshape(shortSignal and not bearishVolumeAnomaly and isVolumeHigher, title="Short+", location=location.abovebar, color=color.rgb(241, 90, 103), transp=0, style=shape.triangledown, text="Short+")
plotshape(longSignal and bullishVolumeAnomaly, title="Long + Anomaly", location=location.belowbar, color=color.rgb(30, 143, 55), transp=0, style=shape.triangleup, text="Long + Anomaly")
plotshape(shortSignal and bearishVolumeAnomaly, title="Short + Anomaly", location=location.abovebar, color=color.rgb(241, 90, 103), transp=0, style=shape.triangledown, text="Short + Anomaly")